### PR TITLE
fix source path to deal with R vs Python version

### PR DESCRIPTION
**Pull request by Lourenzutti**
@trevorcampbell I think this should do it? 

We just need to add it to `rudaux_config.py` something like:

```python
c.source_path = 'R/source'
```

### CODE REVIEW

**Comment by trevorcampbell** [comment]
@Lourenzutti did you test it?

**Comment by Lourenzutti** [comment]
Not yet. I'm glad to do it, though. 

But, our canvas is not published. 
Do we have any test suite/guideline to use for testing that is not a real running course? 
How have you been testing?

**Comment by trevorcampbell** [comment]
It doesn't matter if your canvas page is published -- in fact, it's better if it's not. You can still access it yourself can't you?

I think in this case it will be easiest to use our usual instructor and student servers for testing.

(We do have a test canvas page and a test server, but we'd have to get you set up on those and that will take time)

**Comment by Lourenzutti** [comment]
Hm, but there's the problem of due dates. I can't make rudaux close an assignment because I can't put the due date of an assignment before the term starts. So, rudaux won't clone the repo -- right?

**Comment by Lourenzutti** [comment]
I'll test it after the first deadline. And let you know.

**Comment by trevorcampbell** [comment]
Superceded by #178

**Pull request closed without merging**
